# -*- coding: utf-8 -*-
"""VRPTW_OR_TOOLS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12g9-YuLe-hwZdG45VnVR6gQaQL62217S
"""

from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd gdrive/My Drive/IFT_project

!pip install ortools

!python solver.py --graph data.sample.yaml